Points:
  EnabledFor:
    RangedWeapons: true
    MeleeWeapons: true
    Armor: true
    Pickaxe: true
    Shovel: true
    Axe: true
    FishingRod: true
    Hoe: true
    CurrencySymbol: "$"
    #Should only be enabled if the tools are false
    Tools: false
  Increment:
    PickaxeValues: #Per Block Mined
      Stone: 0.01
      Diorite: 0.01
      Granite: 0.01
      Andesite: 0.01
      Sandstone: 0.01
      ChiseledSandstone: 0.02
      ChiseledRedSandstone: 0.03
      CutSandstone: 0.03
      CutRedSandstone: 0.04
      SmoothSandstone: 0.02
      SmoothRedSandstone: 0.03
      Netherrack: 0.005
      NetherBrick: 0.02
      NetherQuartz: 0.08
      Lapis: 0.1
      Coal: 0.1
      EndStone: 0.05
      Obsidian: 0.08
      Terracotta: 0.03
      Diamond: 0.5
      Emerald: 1.0
      Iron: 0.125
      Gold: 0.25
      Prismarine: 0.05
      PrismarineBricks: 0.05
      Brick: 0.1
      Ice: 0.1
      Other: 0.01
    ShovelValues: #Per Block Excavated
      Sand: 0.01
      SoulSand: 0.02
      Dirt: 0.01
      Mycelium: 0.5
      Gravel: 0.25
    AxeValues: #Per Log Broken (Planks are 1/4 of what is written here)
      Oak: 0.01
      DarkOak: 0.02
      Acacia: 0.05
      Jungle: 0.005
      Spruce: 0.015
      Birch: 0.02
    Fishing: #Per Fish Caught
      Salmon: 0.01
      Cod: 0.02
      Pufferfish: 0.5
      TropicalFish: 1.0
      Other: 0.9
    RangedWeapons: #Per Hit
      Blaze: 0.05
      CaveSpider: 0.03
      Creeper: 0.05
      ElderGuardian: 0.1
      Guardian: 0.05
      EnderDragon: 1.0
      Enderman: 0.08
      Endermite: 0.09
      Evoker: 0.1
      Ghast: 0.05
      Husk: 0.07
      Illusioner: 0.1
      MagmaCube: 0.03
      Phantom: 0.3
      Slime: 0.25
      Stray: 0.5
      Vex: 0.09
      Vindicator: 0.065
      Wither: 1.0
      WitherSkeleton: 0.25
      Witch: 0.26
      Zombie: 0.01
      ZombiePigman: 0.005
      Chicken: 0.005
      Cow: 0.008
      Horse: 0.01
      Llama: 0.02
      MushroomCow: 0.03
      Sheep: 0.008
      Turtle: 0.03
      Pig: 0.01
    MeleeWeapons: #Per Hit
      Blaze: 0.05
      CaveSpider: 0.03
      Creeper: 0.05
      ElderGuardian: 0.1
      Guardian: 0.05
      EnderDragon: 1.0
      Enderman: 0.08
      Endermite: 0.09
      Evoker: 0.1
      Ghast: 0.05
      Husk: 0.07
      Illusioner: 0.1
      MagmaCube: 0.03
      Phantom: 0.3
      Slime: 0.25
      Stray: 0.5
      Vex: 0.09
      Vindicator: 0.065
      Wither: 1.0
      WitherSkeleton: 0.25
      Witch: 0.26
      Zombie: 0.01
      ZombiePigman: 0.005
      Chicken: 0.005
      Cow: 0.008
      Horse: 0.01
      Llama: 0.02
      MushroomCow: 0.03
      Sheep: 0.008
      Turtle: 0.03
      Pig: 0.01
    Hoe:
      Hoe: 1
      ConvertCoarse: 2
    Armor:
      Arrow: 0.01
      Blaze: 0.02
      CaveSpider: 0.02
      Creeper: 0.05
      Drowned: 0.02
      ElderGuardian: 0.1
      Enderman: 0.05
      Endermite: 0.075
      EnderCrystal: 1.0
      EnderDragon: 0.9
      Evoker: 0.1
      Ghast: 0.2
      Giant: 0.9
      Guardian: 0.7
      Husk: 0.1
      Illusioner: 0.4
      IronGolem: 0.5
      Lightning: 1.0
      MagmaCube: 0.5
      Phantom: 0.3
      ZombiePigman: 0.01
      Pillager: 0.02
      Player: 0.05
      PolarBear: 0.05
      Ravager: 0.01
      Shulker: 0.2
      Skeleton: 0.01
      Slime: 0.02
      Spider: 0.02
      Stray: 0.02
      Trident: 0.5
      Vex: 0.02
      Vindicator: 0.03
      Witch: 0.8
      Wither: 0.04
      WitherSkeleton: 0.5
      Wolf: 0.06
      Zombie: 0.01
      ZombieVillager: 0.02
      FallDamage: 0.1
      Other: 0.01
    Tools: 0.1 #per block broken/fish fished
  SQL:
    Enabled: false
    ServerAndPort: "192.168.0.1:3306"
    Database: "database"
    Username: "username"
    Password: "password"