Points:
  #set this to true if you would like PointsCore to act as an economy
  ConnectWithVault: false
  #Available modes are: INTENSE, LIGHT, NONE
  DebugMode: NONE
  #Should it connect to the global server? KEEP THIS FALSE
  #It is still in development and can break your plugin
  ConnectGlobal: false
  #What should be the symbol of the points
  PointsSymbol: "GP"
  PointsName: "General Points"
  PointsDecimalPlaces: 10
  #The Values to add to each tool
  PointType:
    PickaxePoints:
      Name: "Pickaxe Points"
    ShovelPoints:
      Name: "Shovel Points"
    RangedWeaponPoints:
      Name: "Ranged Weapon Points"
    MeleeWeaponPoints:
      Name: "Melee Weapon Points"
    HoePoints:
      Name: "Hoe Points"
    FishingPoints:
      Name: "Fishing Points"
    AxePoints:
      Name: "Axe Points"
    ArmorPoints:
      Name: "Armor Points"
  ##
  ##      INCREMENT SECTION
  ##
  Increment:
    PickaxeValues: #Per Block Mined
      Stone: 0.01
      Diorite: 0.01
      Granite: 0.01
      Andesite: 0.01
      Sandstone: 0.01
      ChiseledSandstone: 0.02
      ChiseledRedSandstone: 0.03
      CutSandstone: 0.03
      RedSandstone: 0.04
      CutRedSandstone: 0.02
      SmoothSandstone: 0.04
      SmoothRedSandstone: 0.03
      Netherrack: 0.005
      NetherBrick: 0.02
      NetherQuartz: 0.08
      Lapis: 0.1
      Coal: 0.1
      EndStone: 0.05
      Obsidian: 0.08
      Terracotta: 0.03
      Diamond: 0.5
      Emerald: 1.0
      Iron: 0.125
      Gold: 0.25
      Copper: 0.1
      CutCopper: 0.06
      CryingObsidian: 10
      Blackstone: 0.01
      Prismarine: 0.05
      PrismarineBricks: 0.05
      Brick: 0.1
      Ice: 0.1
      Deepslate: 0.1
      Redstone: 0.2
      Dripstone: 0.1
      Spawner: 5.00
      Dropper: 0.1
      Observer: 0.1
      Smoker: 0.02
      Rail: 0.001
      Furnace: 0.02
      NetheriteBlock: 7
      AncientDebris: 3
      WaxedCopper: 0.1
      Tuff: 0.1
      Concrete: 0.1
      Other: 0.01
    ShovelValues: #Per Block Excavated
      Sand: 0.01
      SoulSand: 0.02
      Dirt: 0.01
      Mycelium: 0.5
      Mud: 0.3
      Snow: 0.2
      SoulSoil: 0.7
      ConcretePowder: 0.2
      Clay: 0.05
      MuddyMangroveRoots: 1
      Farmland: 0.1
      Podzol: 0.5
      Gravel: 0.25
    AxeValues: #Per Log Broken (Planks are 1/4 of what is written here)
      Oak: 0.01
      DarkOak: 0.02
      Acacia: 0.05
      Jungle: 0.005
      Spruce: 0.015
      Birch: 0.02
      CraftingTable: 0.03
      Chest: 0.04
      Lectern: 0.06
      SmithingTable: 0.08
      Loom: 0.1
      CartographyTable: 0.1
      FletchingTable: 0.1
      Barrel: 0.1
      Jukebox: 0.15
      Campfire: 0.05
      Bookshelf: 0.07
      Banner: 0.02
      JackLantern: 0.07
      Pumpkin: 0.02
      Melon: 0.02
      Sign: 0.02
      Noteblock: 0.02
      MangroveRoots: 0.02
      Beehive: 1
      BeeNest: 0.02
      Composter: 0.5
      MushroomBlock: 0.5
      Bamboo: 0.02
    Fishing: #Per Fish Caught
      Salmon: 0.01
      Cod: 0.02
      Pufferfish: 0.5
      TropicalFish: 1.0
      Other: 0.9
    RangedWeapons: #Per Hit
      Bat: 0.01
      Bee: 0.02
      Blaze: 0.05
      CaveSpider: 0.03
      Cat: 0.03
      Creeper: 0.05
      ElderGuardian: 0.1
      Guardian: 0.05
      EnderDragon: 1.0
      Enderman: 0.08
      Endermite: 0.09
      Evoker: 0.1
      Ghast: 0.05
      Husk: 0.07
      Illusioner: 0.1
      MagmaCube: 0.03
      Phantom: 0.3
      Slime: 0.25
      Stray: 0.5
      Vex: 0.09
      Vindicator: 0.065
      Wither: 1.0
      WitherSkeleton: 0.25
      Witch: 0.26
      Zombie: 0.01
      ZombiePigman: 0.005
      Cod: 0.0005
      SkeletonHorse: 1.0
      Wolf: 0.05
      Donkey: 0.004
      Spider: 0.04
      Player: 2
      Chicken: 0.005
      Cow: 0.008
      Horse: 0.01
      Llama: 0.02
      MushroomCow: 0.03
      Sheep: 0.008
      Turtle: 0.03
      Pig: 0.01
      Other: 0.01
    MeleeWeapons: #Per Hit
      Bat: 0.01
      Bee: 0.02
      Blaze: 0.05
      CaveSpider: 0.03
      Cat: 0.03
      Creeper: 0.05
      ElderGuardian: 0.1
      Guardian: 0.05
      EnderDragon: 1.0
      Enderman: 0.08
      Endermite: 0.09
      Evoker: 0.1
      Ghast: 0.05
      Husk: 0.07
      Illusioner: 0.1
      MagmaCube: 0.03
      Phantom: 0.3
      Slime: 0.25
      Stray: 0.5
      Vex: 0.09
      Vindicator: 0.065
      Wither: 1.0
      WitherSkeleton: 0.25
      Witch: 0.26
      Zombie: 0.01
      ZombiePigman: 0.005
      Chicken: 0.005
      Cow: 0.008
      Horse: 0.01
      Llama: 0.02
      MushroomCow: 0.03
      Sheep: 0.008
      Turtle: 0.03
      Pig: 0.01
      Other: 0.01
    Hoe:
      Hoe: 1
      ConvertCoarse: 2
    Armor:
      Blaze: 0.02
      CaveSpider: 0.02
      Creeper: 0.05
      Drowned: 0.02
      ElderGuardian: 0.1
      Enderman: 0.05
      Endermite: 0.075
      EnderCrystal: 1.0
      EnderDragon: 0.9
      Evoker: 0.1
      Ghast: 0.2
      Giant: 0.9
      Guardian: 0.7
      Husk: 0.1
      Illusioner: 0.4
      IronGolem: 0.5
      Lightning: 1.0
      MagmaCube: 0.5
      Phantom: 0.3
      ZombiePigman: 0.01
      Pillager: 0.02
      Player: 0.05
      PolarBear: 0.05
      Ravager: 0.01
      Shulker: 0.2
      Skeleton: 0.01
      Slime: 0.02
      Spider: 0.02
      Stray: 0.02
      Trident: 0.5
      Vex: 0.02
      Vindicator: 0.03
      Witch: 0.8
      Wither: 0.04
      WitherSkeleton: 0.5
      Wolf: 0.06
      Zombie: 0.01
      ZombieVillager: 0.02
      FallDamage: 0.1
      Fireball: 0.1
      DragonFireball: 1.0
      Other: 0.01
    Tools: 0.1 #per block broken/fish fished
  #SQL DB settings
  SQL:
    Enabled: false
    ServerAndPort: "192.168.0.1:3306"
    Database: "database"
    Username: "username"
    Password: "password"
QuitMessage: ":player: &#17fb04p&#2bf61ae&#40f131a&#54ec47c&#68e75ee&#7de274d &#91dd8bo&#a5d8a1u&#bad3b8t&#cecece."
CustomJoinMessage: ":player: &#17fb04d&#21f90fr&#2af619o&#34f424p&#3ef22fp&#47ef39e&#51ed44d &#5aea4ei&#64e859n&#6ee664t&#77e36eo &#81e179t&#8bdf84h&#94dc8ee &#9eda99w&#a7d7a3o&#b1d5aer&#bbd3b9l&#c4d0c3d&#cecece."
CustomDeathMessage:
  BLOCK_EXPLOSION: ":player: &#17fb04e&#2ef51dx&#45f037p&#5cea50l&#73e569o&#89df82d&#a0d99ce&#b7d4b5d&#cecece."
  CONTACT: ":player: &#17fb04h&#21f90fu&#2af619g&#34f424g&#3ef22fe&#47ef39d &#51ed44t&#5aea4eh&#64e859e &#6ee664w&#77e36er&#81e179o&#8bdf84n&#94dc8eg &#9eda99b&#a7d7a3l&#b1d5aeo&#bbd3b9c&#c4d0c3k&#cecece."
  CRAMMING: ":player: &#17fb04g&#28f716o&#38f329t &#49ef3bs&#5aeb4dq&#6ae760u&#7be272i&#8bde85s&#9cda97h&#add6a9e&#bdd2bcd&#cecece."
  CUSTOM: ":player: &#17fb04d&#28f716i&#38f329e&#49ef3bd &#5aeb4dw&#6ae760i&#7be272e&#8bde85r&#9cda97d&#add6a9l&#bdd2bcy&#cecece."
  DRAGON_BREATH: ":player: &#17fb04d&#21f90fi&#2af619e&#34f424d &#3ef22fo&#47ef39f &#51ed44a &#5aea4es&#64e859t&#6ee664i&#77e36en&#81e179k&#8bdf84y &#94dc8eb&#9eda99r&#a7d7a3e&#b1d5aea&#bbd3b9t&#c4d0c3h&#cecece."
  DROWNING: ":player: &#17fb04t&#1dfa0bh&#23f811o&#29f718u&#2ff51fg&#36f426h&#3cf22ct &#42f133t&#48ef3ah&#4eee41e&#54ec47y &#5aeb4ec&#60e955o&#66e85cu&#6ce662l&#73e569d &#79e370b&#7fe276r&#85e07de&#8bdf84a&#91dd8bt&#97dc91h&#9dda98e &#a3d99fi&#a9d7a6n &#b0d6acw&#b6d4b3a&#bcd3bat&#c2d1c1e&#c8d0c7r&#cecece."
  ENTITY_ATTACK: ":player: &#17fb04g&#26f715o&#36f426t &#45f037b&#54ec47u&#63e858t&#73e569c&#82e17ah&#91dd8be&#a0d99cr&#b0d6ace&#bfd2bdd&#cecece."
  ENTITY_EXPLOSION: ":player: &#17fb04w&#1ff90ca&#26f715s &#2ef51dc&#36f426r&#3df22ee&#45f037e&#4cee3fp&#54ec47e&#5cea50d &#63e858o&#6be661u&#73e569t &#7ae371o&#82e17af &#89df82t&#91dd8bh&#99db93i&#a0d99cs &#a8d7a4w&#b0d6aco&#b7d4b5r&#bfd2bdl&#c6d0c6d&#cecece."
  ENTITY_SWEEP_ATTACK: ":player: &#17fb04w&#1ff90ca&#26f715s &#2ef51ds&#36f426w&#3df22ee&#45f037e&#4cee3fp&#54ec47e&#5cea50d &#63e858o&#6be661u&#73e569t &#7ae371o&#82e17af &#89df82t&#91dd8bh&#99db93i&#a0d99cs &#a8d7a4w&#b0d6aco&#b7d4b5r&#bfd2bdl&#c6d0c6d&#cecece."
  FALL: ":player: &#17fb04f&#28f716e&#38f329l&#49ef3bl &#5aeb4dt&#6ae760o&#7be272o &#8bde85h&#9cda97a&#add6a9r&#bdd2bcd&#cecece."
  FALLING_BLOCK: ":player: &#17fb04g&#1ff90do&#28f716t &#30f520h&#38f329i&#41f132t &#49ef3bt&#51ed44o&#5aeb4do &#62e957h&#6ae760a&#73e569r&#7be272d &#83e07bo&#8bde85n &#94dc8et&#9cda97h&#a4d8a0e &#add6a9h&#b5d4b2e&#bdd2bca&#c6d0c5d&#cecece."
  FIRE: ":player: &#17fb04b&#29f718u&#3cf22cr&#4eee41n&#60e955e&#73e569d &#85e07da &#97dc91l&#a9d7a6o&#bcd3bat&#cecece."
  FIRE_TICK: ":player: &#17fb04t&#21f90fh&#2af619o&#34f424u&#3ef22fg&#47ef39h&#51ed44t &#5aea4eh&#64e859e &#6ee664w&#77e36ea&#81e179s &#8bdf84a &#94dc8ec&#9eda99a&#a7d7a3n&#b1d5aed&#bbd3b9l&#c4d0c3e&#cecece."
  FLY_INTO_WALL: ":player: &#17fb04f&#25f814l&#33f423e&#41f133w &#4fed42i&#5dea52n&#6be661t&#7ae371o &#88df80a &#96dc90w&#a4d89fa&#b2d5afl&#c0d1bel&#cecece."
  FREEZE: ":player: &#17fb04b&#24f812e&#31f521c&#3ef12fa&#4bee3em&#58eb4ce &#65e85bi&#73e569c&#80e177e &#8dde86c&#9adb94r&#a7d8a3e&#b4d4b1a&#c1d1c0m&#cecece."
  HOT_FLOOR: ":player: &#17fb04b&#20f90eu&#29f718r&#32f422n&#3cf22ce&#45f037d &#4eee41h&#57eb4bi&#60e955s &#69e75ff&#73e569e&#7ce273e&#85e07dt &#8ede87t&#97dc91o&#a0d99co &#a9d7a6h&#b3d5b0a&#bcd3bar&#c5d0c4d&#cecece."
  LAVA: ":player: &#17fb04m&#22f810e&#2df61cl&#37f328t&#42f034e&#4dee3fd &#58eb4bi&#62e857n&#6de663t&#78e36fo &#83e17ba &#8dde87p&#98db93u&#a3d99ed&#aed6aad&#b8d3b6l&#c3d1c2e&#cecece."
  LIGHTNING: ":player: &#17fb04w&#1dfa0bo&#23f811n &#29f718t&#2ff51eh&#35f425e &#3af22bl&#40f132i&#46ef38g&#4cee3fh&#52ec45t&#58eb4cn&#5eea52i&#64e859n&#6ae75fg &#70e566j&#75e46ca&#7be273c&#81e179k&#87df80p&#8dde86o&#93dd8dt&#99db93. &#9fda9aT&#a5d8a0h&#abd7a7e&#b0d5adn &#b6d4b4d&#bcd2bai&#c2d1c1e&#c8cfc7d&#cecece."
  MAGIC: ":player: &#17fb04w&#21f90fa&#2bf61as &#36f426i&#40f131n &#4aef3ct&#54ec47h&#5eea53e &#68e75es&#73e569p&#7de274l&#87e07fa&#91dd8bs&#9bdb96h &#a5d8a1z&#b0d6aco&#bad3b8n&#c4d1c3e&#cecece."
  POISON: ":player: &#17fb04a&#22f810t&#2df61ce &#37f328s&#42f034o&#4dee3fm&#58eb4be&#62e857t&#6de663h&#78e36fi&#83e17bn&#8dde87g &#98db93w&#a3d99er&#aed6aao&#b8d3b6n&#c3d1c2g&#cecece."
  PROJECTILE: ":player: &#17fb04g&#23f811o&#2ff51ft &#3cf22ch&#48ef3ai&#54ec47t &#60e955i&#6ce662n &#79e370t&#85e07dh&#91dd8be &#9dda98h&#a9d7a6e&#b6d4b3a&#c2d1c1d&#cecece."
  SONIC_BOOM: ":player: &#17fb04i&#1ef90cs &#26f714n&#2df61co&#34f424w &#3cf22cc&#43f034a&#4aee3dn&#52ed45c&#59eb4de&#60e955l&#68e75dl&#6fe565e&#76e46dd &#7de275b&#85e07dy &#8cde85t&#93dc8dh&#9bdb95e &#a2d99eW&#a9d7a6a&#b1d5aer&#b8d3b6d&#bfd2bee&#c7d0c6n&#cecece."
  STARVATION: ":player: &#17fb04f&#28f716o&#38f329r&#49ef3bg&#5aeb4do&#6ae760t &#7be272t&#8bde85o &#9cda97e&#add6a9a&#bdd2bct&#cecece."
  SUFFOCATION: ":player: &#17fb04d&#1ef90ci&#26f714e&#2df61cd &#34f424i&#3cf22cn &#43f034a &#4aee3dh&#52ed45o&#59eb4dl&#60e955e&#68e75d, &#6fe565d&#76e46di&#7de275e&#85e07dd &#8cde85i&#93dc8dn &#9bdb95t&#a2d99eh&#a9d7a6e &#b1d5aew&#b8d3b6a&#bfd2bel&#c7d0c6l&#cecece."
  SUICIDE: ":player: &#17fb04d&#1dfa0be&#23f811c&#29f718i&#2ff51fd&#36f426e&#3cf22cd &#42f133t&#48ef3ao &#4eee41e&#54ec47n&#5aeb4ed &#60e955t&#66e85ch&#6ce662e&#73e569i&#79e370r &#7fe276m&#85e07di&#8bdf84s&#91dd8be&#97dc91r&#9dda98a&#a3d99fb&#a9d7a6l&#b0d6ace &#b6d4b3l&#bcd3bai&#c2d1c1f&#c8d0c7e&#cecece."
  THORNS: ":player: &#17fb04h&#25f814i&#33f423t &#41f133t&#4fed42h&#5dea52e&#6be661m&#7ae371s&#88df80e&#96dc90l&#a4d89fv&#b2d5afe&#c0d1bes&#cecece."
  VOID: ":player: &#17fb04s&#1dfa0au&#22f810r&#28f716f&#2df61ce&#33f423d &#38f329l&#3ef12fi&#43f035f&#49ef3be &#4eed41a&#54ec47n&#5aeb4dd &#5fe954d&#65e85ae&#6ae760a&#70e566t&#75e46ch&#7be272, &#80e178t&#86e07eh&#8bde85e&#91dd8bn &#97dc91c&#9cda97h&#a2d99do&#a7d8a3s&#add6a9e &#b2d5afd&#b8d3b6e&#bdd2bca&#c3d1c2t&#c8cfc8h&#cecece."
  WITHER: ":player: &#17fb04w&#26f715i&#36f426t&#45f037h&#54ec47e&#63e858r&#73e569e&#82e17ad &#91dd8ba&#a0d99cw&#b0d6aca&#bfd2bdy&#cecece."

