name: PointsCore
author: marcangeloh
api-version: 1.19
version: ${project.version}
description: The Ultimate points plugin with an easy to use API.
main: me.marcangeloh.PointsCore
softdepend:
  - PlaceholderAPI
  - Vault
commands:
  pointcheck:
    aliases: [pc]
    description: Check the amount of points
    default: false
    usage: /pointcheck <playername>
  points:
    add:
      description: Add points to player
      default: op
      usage: /points add <player> <type> <amount>
    remove:
      description: Remove points from player
      default: op
      usage: /points remove <player> <type> <amount>
    multiplier:
      description: Sets a players point multiplier
      default: op
      usage: /points set <player> <duration> <amount>
    reload:
      description: Reloads the config file
      default: op
      usage: /points reload
    help:
      description: Sends the help message
      default: op
      usage: /points help
  hologram:
    aliases: holo
    create:
      aliases: add
      description: Creates a hologram at players location
      default: op
      usage: /hologram create
    delete:
      aliases: remove
      description: Removes all holograms in <radius> of player
      default: op
      usage: /hologram delete <radius>
  randomtp:
    aliases:
      - rtp
      - wild
    description: Teleports the player to a random location
    default: true
    usage: /rtp
  tpa:
    aliases:
      - tpahere
    description: Teleports the player to another player
    usage: /tpa <player>
    default: true
  tpaccept:
    aliases:
      - tpdeny
      - tpcancel
    description: Accepts or rejects the teleport request
    usage: /tpaccept
    default: true
  fly:
    description: Allows the player to fly
    default: op
    usage: /fly
  broadcast:
    description: Broadcast a nessage to all players
    aliases:
      - bc
    default: op
    usage: /broadcast <message>
  god:
    description: Grants invulnerability
    aliases:
      - godmode
    default: op
    usage: /god <player>
  heal:
    description: Heals the player
    default: op
    usage: /heal <player>
  vanish:
    aliases:
      - v
    description: Vanish into thin air
    default: op
    usage: /vanish <player>
