name: PointsCore
author: marcangeloh
api-version: 1.16
version: 1.1.6
description: The Ultimate points plugin with an easy to use API.
main: me.marcangeloh.PointsCore
softdepend:
  - PlaceholderAPI
  - Vault
commands:
  pointcheck:
    aliases: [pc]
    description: Check the amount of points
    default: false
    usage: /pointcheck <playername>
  points:
    description: Basic command for PointsCore
    default: op
    usage: /points help