package me.marcangeloh.API.Util.ConfigurationUtil;

import me.marcangeloh.API.Util.GeneralUtil.Tools;
import org.bukkit.Material;

public class ToolUtil {
    public static Tools getToolTypeForMaterial(Material material) {
        switch (material) {
            case BAMBOO_STAIRS:
            case BAMBOO:
            case BAMBOO_BLOCK:
            case BAMBOO_BUTTON:
            case BAMBOO_CHEST_RAFT:
            case BAMBOO_DOOR:
            case BAMBOO_FENCE:
            case BAMBOO_FENCE_GATE:
            case BAMBOO_HANGING_SIGN:
            case BAMBOO_MOSAIC:
            case BAMBOO_MOSAIC_SLAB:
            case BAMBOO_MOSAIC_STAIRS:
            case BAMBOO_PLANKS:
            case BAMBOO_PRESSURE_PLATE:
            case BAMBOO_RAFT:
            case BAMBOO_SLAB:
            case BAMBOO_TRAPDOOR:
            case BAMBOO_SIGN:
            case BAMBOO_WALL_HANGING_SIGN:
            case BAMBOO_WALL_SIGN:
            case OAK_BOAT:
            case OAK_BUTTON:
            case OAK_CHEST_BOAT:
            case OAK_DOOR:
            case OAK_FENCE:
            case OAK_FENCE_GATE:
            case OAK_HANGING_SIGN:
            case OAK_LOG:
            case OAK_PLANKS:
            case OAK_PRESSURE_PLATE:
            case OAK_SIGN:
            case OAK_SLAB:
            case OAK_STAIRS:
            case OAK_TRAPDOOR:
            case OAK_WALL_SIGN:
            case OAK_WOOD:
            case OAK_WALL_HANGING_SIGN:
            case DARK_OAK_BOAT:
            case DARK_OAK_BUTTON:
            case DARK_OAK_CHEST_BOAT:
            case DARK_OAK_DOOR:
            case DARK_OAK_FENCE:
            case DARK_OAK_FENCE_GATE:
            case DARK_OAK_HANGING_SIGN:
            case DARK_OAK_LOG:
            case DARK_OAK_PLANKS:
            case DARK_OAK_PRESSURE_PLATE:
            case DARK_OAK_SIGN:
            case DARK_OAK_SLAB:
            case DARK_OAK_STAIRS:
            case DARK_OAK_TRAPDOOR:
            case DARK_OAK_WALL_HANGING_SIGN:
            case DARK_OAK_WALL_SIGN:
            case DARK_OAK_WOOD:
            case JUNGLE_BOAT:
            case JUNGLE_BUTTON:
            case JUNGLE_CHEST_BOAT:
            case JUNGLE_DOOR:
            case JUNGLE_FENCE:
            case JUNGLE_FENCE_GATE:
            case JUNGLE_HANGING_SIGN:
            case JUNGLE_LOG:
            case JUNGLE_PLANKS:
            case JUNGLE_SIGN:
            case JUNGLE_PRESSURE_PLATE:
            case JUNGLE_SLAB:
            case JUNGLE_STAIRS:
            case JUNGLE_TRAPDOOR:
            case JUNGLE_WOOD:
            case JUNGLE_WALL_HANGING_SIGN:
            case JUNGLE_WALL_SIGN:
            case BIRCH_BOAT:
            case BIRCH_BUTTON:
            case BIRCH_CHEST_BOAT:
            case BIRCH_DOOR:
            case BIRCH_FENCE:
            case BIRCH_FENCE_GATE:
            case BIRCH_HANGING_SIGN:
            case BIRCH_LOG:
            case BIRCH_PLANKS:
            case BIRCH_PRESSURE_PLATE:
            case BIRCH_SIGN:
            case BIRCH_SLAB:
            case BIRCH_STAIRS:
            case BIRCH_TRAPDOOR:
            case BIRCH_WOOD:
            case BIRCH_WALL_HANGING_SIGN:
            case BIRCH_WALL_SIGN:
            case ACACIA_LOG:
            case ACACIA_BOAT:
            case ACACIA_BUTTON:
            case ACACIA_CHEST_BOAT:
            case ACACIA_DOOR:
            case ACACIA_FENCE:
            case ACACIA_FENCE_GATE:
            case ACACIA_HANGING_SIGN:
            case ACACIA_PLANKS:
            case ACACIA_PRESSURE_PLATE:
            case ACACIA_SIGN:
            case ACACIA_SLAB:
            case ACACIA_STAIRS:
            case ACACIA_TRAPDOOR:
            case ACACIA_WOOD:
            case ACACIA_WALL_HANGING_SIGN:
            case ACACIA_WALL_SIGN:
            case MANGROVE_LOG:
            case MANGROVE_BOAT:
            case MANGROVE_BUTTON:
            case MANGROVE_CHEST_BOAT:
            case MANGROVE_DOOR:
            case MANGROVE_FENCE:
            case MANGROVE_FENCE_GATE:
            case MANGROVE_HANGING_SIGN:
            case MANGROVE_PLANKS:
            case MANGROVE_PROPAGULE:
            case MANGROVE_ROOTS:
            case MANGROVE_SIGN:
            case MANGROVE_SLAB:
            case MANGROVE_STAIRS:
            case MANGROVE_TRAPDOOR:
            case MANGROVE_PRESSURE_PLATE:
            case MANGROVE_WALL_SIGN:
            case MANGROVE_WOOD:
            case MANGROVE_WALL_HANGING_SIGN:
            case SPRUCE_LOG:
            case SPRUCE_BOAT:
            case SPRUCE_BUTTON:
            case SPRUCE_CHEST_BOAT:
            case SPRUCE_DOOR:
            case SPRUCE_FENCE:
            case SPRUCE_FENCE_GATE:
            case SPRUCE_HANGING_SIGN:
            case SPRUCE_PLANKS:
            case SPRUCE_PRESSURE_PLATE:
            case SPRUCE_SIGN:
            case SPRUCE_SLAB:
            case SPRUCE_STAIRS:
            case SPRUCE_TRAPDOOR:
            case SPRUCE_WOOD:
            case SPRUCE_WALL_HANGING_SIGN:
            case SPRUCE_WALL_SIGN:
            case CHEST:
            case CRAFTING_TABLE:
            case STRIPPED_ACACIA_LOG:
            case STRIPPED_ACACIA_WOOD:
            case STRIPPED_BAMBOO_BLOCK:
            case STRIPPED_BIRCH_LOG:
            case STRIPPED_BIRCH_WOOD:
            case STRIPPED_CRIMSON_HYPHAE:
            case CRIMSON_HYPHAE:
            case CRIMSON_BUTTON:
            case CRIMSON_DOOR:
            case CRIMSON_FENCE:
            case CRIMSON_FENCE_GATE:
            case CRIMSON_HANGING_SIGN:
            case CRIMSON_PLANKS:
            case CRIMSON_ROOTS:
            case CRIMSON_PRESSURE_PLATE:
            case CRIMSON_SIGN:
            case CRIMSON_SLAB:
            case CRIMSON_STAIRS:
            case CRIMSON_STEM:
            case CRIMSON_TRAPDOOR:
            case CRIMSON_WALL_HANGING_SIGN:
            case CRIMSON_WALL_SIGN:
            case TRAPPED_CHEST:
            case WARPED_BUTTON:
            case WARPED_DOOR:
            case WARPED_FENCE:
            case WARPED_FENCE_GATE:
            case WARPED_PLANKS:
            case WARPED_PRESSURE_PLATE:
            case WARPED_ROOTS:
            case WARPED_STAIRS:
            case WARPED_SIGN:
            case WARPED_HANGING_SIGN:
            case WARPED_TRAPDOOR:
            case WARPED_WALL_HANGING_SIGN:
            case WARPED_WALL_SIGN:
            case WARPED_SLAB:
            case JUKEBOX:
            case NOTE_BLOCK:
            case FLETCHING_TABLE:
            case CARTOGRAPHY_TABLE:
            case BOOKSHELF:
            case CHISELED_BOOKSHELF:
            case LECTERN:
                return Tools.AXE;
            case DIRT:
            case DIRT_PATH:
            case COARSE_DIRT:
            case ROOTED_DIRT:
            case GRASS_BLOCK:
            case SNOW_BLOCK:
            case POWDER_SNOW:
            case SNOW:
            case SAND:
            case SOUL_SAND:
            case GRAVEL:
            case RED_SAND:
            case MYCELIUM:
            case FARMLAND:
            case MUD:
            case MUDDY_MANGROVE_ROOTS:
            case BLACK_CONCRETE_POWDER:
            case BLUE_CONCRETE_POWDER:
            case PINK_CONCRETE_POWDER:
            case BROWN_CONCRETE_POWDER:
            case CYAN_CONCRETE_POWDER:
            case GRAY_CONCRETE_POWDER:
            case GREEN_CONCRETE_POWDER:
            case LIGHT_BLUE_CONCRETE_POWDER:
            case LIGHT_GRAY_CONCRETE_POWDER:
            case LIME_CONCRETE_POWDER:
            case MAGENTA_CONCRETE_POWDER:
            case ORANGE_CONCRETE_POWDER:
            case PURPLE_CONCRETE_POWDER:
            case RED_CONCRETE_POWDER:
            case WHITE_CONCRETE_POWDER:
            case YELLOW_CONCRETE_POWDER:
            case SOUL_SOIL:
            case PODZOL:
                return Tools.SHOVEL;
            case OBSIDIAN:
            case ANCIENT_DEBRIS:
            case CRYING_OBSIDIAN:
            case RESPAWN_ANCHOR:
            case ENDER_CHEST:
            case ANVIL:
            case COAL_BLOCK:
            case DIAMOND_BLOCK:
            case NETHERITE_BLOCK:
            case EMERALD_BLOCK:
            case IRON_BLOCK:
            case REDSTONE_BLOCK:
            case GOLD_BLOCK:
            case ENCHANTING_TABLE:
            case IRON_BARS:
            case IRON_DOOR:
            case IRON_TRAPDOOR:
            case SPAWNER:
            case BELL:
            case DISPENSER:
            case DROPPER:
            case OBSERVER:
            case FURNACE:
            case BLAST_FURNACE:
            case SMOKER:
            case STONECUTTER:
            case LODESTONE:
            case LANTERN:
            case CONDUIT:
            case COAL_ORE:
            case DRAGON_EGG:
            case DIAMOND_ORE:
            case EMERALD_ORE:
            case END_STONE:
            case GOLD_ORE:
            case HOPPER:
            case IRON_ORE:
            case LAPIS_BLOCK:
            case LAPIS_ORE:
            case NETHER_QUARTZ_ORE:
            case NETHER_GOLD_ORE:
            case REDSTONE_ORE:
            case GRINDSTONE:
            case BONE_BLOCK:
            case BRICK_STAIRS:
            case BRICKS:
            case BRICK_SLAB:
            case BRICK_WALL:
            case CAULDRON:
            case COBBLESTONE:
            case COBBLESTONE_SLAB:
            case COBBLESTONE_WALL:
            case COBBLESTONE_STAIRS:
            case MOSSY_COBBLESTONE:
            case NETHER_BRICKS:
            case RED_NETHER_BRICKS:
            case NETHER_BRICK_FENCE:
            case NETHER_BRICK_STAIRS:
            case STONE_SLAB:
            case POLISHED_BLACKSTONE:
            case RED_CONCRETE:
            case BLACK_CONCRETE:
            case BLUE_CONCRETE:
            case CYAN_CONCRETE:
            case BROWN_CONCRETE:
            case GRAY_CONCRETE:
            case GREEN_CONCRETE:
            case LIGHT_BLUE_CONCRETE:
            case LIGHT_GRAY_CONCRETE:
            case LIME_CONCRETE:
            case MAGENTA_CONCRETE:
            case ORANGE_CONCRETE:
            case PINK_CONCRETE:
            case PURPLE_CONCRETE:
            case WHITE_CONCRETE:
            case YELLOW_CONCRETE:
            case SHULKER_BOX:
            case ANDESITE:
            case ANDESITE_SLAB:
            case ANDESITE_WALL:
            case ANDESITE_STAIRS:
            case DARK_PRISMARINE:
            case DIORITE:
            case DIORITE_SLAB:
            case DIORITE_WALL:
            case DIORITE_STAIRS:
            case GRANITE:
            case GRANITE_SLAB:
            case GRANITE_WALL:
            case GRANITE_STAIRS:
            case POLISHED_GRANITE:
            case PRISMARINE:
            case PRISMARINE_SLAB:
            case PRISMARINE_STAIRS:
            case PRISMARINE_BRICK_SLAB:
            case PRISMARINE_BRICK_STAIRS:
            case PRISMARINE_BRICKS:
            case STONE:
            case SMOOTH_SANDSTONE:
            case SMOOTH_STONE:
            case PURPUR_BLOCK:
            case PURPUR_PILLAR:
            case PURPUR_SLAB:
            case PURPUR_STAIRS:
            case SANDSTONE:
            case SANDSTONE_SLAB:
            case SANDSTONE_STAIRS:
            case SANDSTONE_WALL:
            case SMOOTH_RED_SANDSTONE:
            case STONE_BRICK_SLAB:
            case STONE_BRICK_STAIRS:
            case STONE_BRICK_WALL:
            case STONE_BRICKS:
            case BLACKSTONE:
            case BLACKSTONE_SLAB:
            case BLACKSTONE_STAIRS:
            case BLACKSTONE_WALL:
            case BLACK_SHULKER_BOX:
            case BLUE_SHULKER_BOX:
            case BROWN_SHULKER_BOX:
            case CYAN_SHULKER_BOX:
            case GRAY_SHULKER_BOX:
            case GREEN_SHULKER_BOX:
            case LIGHT_BLUE_SHULKER_BOX:
            case LIME_SHULKER_BOX:
            case MAGENTA_SHULKER_BOX:
            case ORANGE_SHULKER_BOX:
            case PINK_SHULKER_BOX:
            case PURPLE_SHULKER_BOX:
            case RED_SHULKER_BOX:
            case WHITE_SHULKER_BOX:
            case YELLOW_SHULKER_BOX:
            case LIGHT_GRAY_SHULKER_BOX:
            case CHISELED_POLISHED_BLACKSTONE:
            case CHISELED_STONE_BRICKS:
            case POLISHED_ANDESITE:
            case POLISHED_ANDESITE_SLAB:
            case POLISHED_ANDESITE_STAIRS:
            case POLISHED_BASALT:
            case POLISHED_BLACKSTONE_BRICK_SLAB:
            case POLISHED_BLACKSTONE_BRICK_STAIRS:
            case POLISHED_BLACKSTONE_BRICK_WALL:
            case POLISHED_BLACKSTONE_BRICKS:
            case POLISHED_BLACKSTONE_BUTTON:
            case POLISHED_BLACKSTONE_PRESSURE_PLATE:
            case POLISHED_BLACKSTONE_SLAB:
            case POLISHED_BLACKSTONE_STAIRS:
            case POLISHED_BLACKSTONE_WALL:
            case POLISHED_DEEPSLATE:
            case POLISHED_DEEPSLATE_SLAB:
            case POLISHED_DEEPSLATE_STAIRS:
            case POLISHED_DIORITE:
            case POLISHED_DIORITE_SLAB:
            case POLISHED_DIORITE_STAIRS:
            case POLISHED_DEEPSLATE_WALL:
            case POLISHED_GRANITE_SLAB:
            case POLISHED_GRANITE_STAIRS:
            case GILDED_BLACKSTONE:
            case BLACK_GLAZED_TERRACOTTA:
            case GRAY_GLAZED_TERRACOTTA:
            case RED_GLAZED_TERRACOTTA:
            case BLUE_GLAZED_TERRACOTTA:
            case CYAN_GLAZED_TERRACOTTA:
            case LIME_GLAZED_TERRACOTTA:
            case PINK_GLAZED_TERRACOTTA:
            case BROWN_GLAZED_TERRACOTTA:
            case GREEN_GLAZED_TERRACOTTA:
            case WHITE_GLAZED_TERRACOTTA:
            case ORANGE_GLAZED_TERRACOTTA:
            case PURPLE_GLAZED_TERRACOTTA:
            case YELLOW_GLAZED_TERRACOTTA:
            case MAGENTA_GLAZED_TERRACOTTA:
            case LIGHT_BLUE_GLAZED_TERRACOTTA:
            case LIGHT_GRAY_GLAZED_TERRACOTTA:
            case TERRACOTTA:
            case RED_TERRACOTTA:
            case BLUE_TERRACOTTA:
            case CYAN_TERRACOTTA:
            case GRAY_TERRACOTTA:
            case LIME_TERRACOTTA:
            case PINK_TERRACOTTA:
            case BLACK_TERRACOTTA:
            case BROWN_TERRACOTTA:
            case GREEN_TERRACOTTA:
            case WHITE_TERRACOTTA:
            case ORANGE_TERRACOTTA:
            case PURPLE_TERRACOTTA:
            case YELLOW_TERRACOTTA:
            case MAGENTA_TERRACOTTA:
            case LIGHT_BLUE_TERRACOTTA:
            case LIGHT_GRAY_TERRACOTTA:
            case BASALT:
            case SMOOTH_BASALT:
            case QUARTZ:
            case QUARTZ_BLOCK:
            case QUARTZ_BRICKS:
            case QUARTZ_PILLAR:
            case QUARTZ_SLAB:
            case QUARTZ_STAIRS:
            case CHISELED_QUARTZ_BLOCK:
            case SMOOTH_QUARTZ:
            case SMOOTH_QUARTZ_SLAB:
            case SMOOTH_QUARTZ_STAIRS:
            case RED_SANDSTONE:
            case RED_SANDSTONE_SLAB:
            case RED_SANDSTONE_WALL:
            case RED_SANDSTONE_STAIRS:
            case CUT_RED_SANDSTONE:
            case CHISELED_RED_SANDSTONE:
            case CUT_RED_SANDSTONE_SLAB:
            case SMOOTH_RED_SANDSTONE_SLAB:
            case SMOOTH_RED_SANDSTONE_STAIRS:
            case CUT_SANDSTONE:
            case CHISELED_SANDSTONE:
            case SMOOTH_SANDSTONE_SLAB:
            case SMOOTH_SANDSTONE_STAIRS:
            case CUT_SANDSTONE_SLAB:
            case WARPED_NYLIUM:
            case CRIMSON_NYLIUM:
            case RAIL:
            case POWERED_RAIL:
            case DETECTOR_RAIL:
            case ACTIVATOR_RAIL:
            case BREWING_STAND:
            case BLUE_ICE:
            case ICE:
            case MAGMA_BLOCK:
            case PACKED_ICE:
            case FROSTED_ICE:
            case NETHERRACK:
            case END_ROD:
            case DEEPSLATE:
            case DEEPSLATE_BRICK_SLAB:
            case DEEPSLATE_BRICK_STAIRS:
            case DEEPSLATE_BRICK_WALL:
            case DEEPSLATE_BRICKS:
            case DEEPSLATE_COAL_ORE:
            case DEEPSLATE_COPPER_ORE:
            case DEEPSLATE_DIAMOND_ORE:
            case COPPER_BLOCK:
            case COPPER_ORE:
            case CUT_COPPER:
            case CUT_COPPER_SLAB:
            case CUT_COPPER_STAIRS:
            case EXPOSED_CUT_COPPER:
            case EXPOSED_COPPER:
            case RAW_COPPER_BLOCK:
            case WAXED_CUT_COPPER:
            case WAXED_CUT_COPPER_SLAB:
            case WAXED_CUT_COPPER_STAIRS:
            case WAXED_EXPOSED_COPPER:
            case WAXED_EXPOSED_CUT_COPPER:
            case WAXED_EXPOSED_CUT_COPPER_SLAB:
            case WAXED_OXIDIZED_CUT_COPPER:
            case OXIDIZED_COPPER:
            case OXIDIZED_CUT_COPPER:
            case OXIDIZED_CUT_COPPER_SLAB:
            case OXIDIZED_CUT_COPPER_STAIRS:
            case WAXED_COPPER_BLOCK:
            case WAXED_OXIDIZED_COPPER:
            case WAXED_EXPOSED_CUT_COPPER_STAIRS:
            case WAXED_OXIDIZED_CUT_COPPER_SLAB:
            case WAXED_OXIDIZED_CUT_COPPER_STAIRS:
            case WAXED_WEATHERED_COPPER:
            case WAXED_WEATHERED_CUT_COPPER:
            case WAXED_WEATHERED_CUT_COPPER_SLAB:
            case WAXED_WEATHERED_CUT_COPPER_STAIRS:
            case WEATHERED_COPPER:
            case WEATHERED_CUT_COPPER:
            case WEATHERED_CUT_COPPER_SLAB:
            case WEATHERED_CUT_COPPER_STAIRS:
            case DEEPSLATE_GOLD_ORE:
            case DEEPSLATE_EMERALD_ORE:
            case DEEPSLATE_IRON_ORE:
            case DEEPSLATE_LAPIS_ORE:
            case DEEPSLATE_REDSTONE_ORE:
            case BRAIN_CORAL_BLOCK:
            case BUBBLE_CORAL_BLOCK:
            case AMETHYST_BLOCK:
            case DRIPSTONE_BLOCK:
            case DEAD_BRAIN_CORAL_BLOCK:
            case DEAD_BUBBLE_CORAL_BLOCK:
            case DEAD_FIRE_CORAL_BLOCK:
            case BRAIN_CORAL:
            case BUBBLE_CORAL:
            case DEAD_BRAIN_CORAL:
            case DEAD_BUBBLE_CORAL:
            case DEAD_FIRE_CORAL:
            case DEAD_HORN_CORAL:
            case DEAD_TUBE_CORAL:
            case FIRE_CORAL:
            case HORN_CORAL:
            case TUBE_CORAL:
            case BRAIN_CORAL_FAN:
            case BUBBLE_CORAL_FAN:
            case BRAIN_CORAL_WALL_FAN:
            case FIRE_CORAL_FAN:
            case FIRE_CORAL_WALL_FAN:
            case BUBBLE_CORAL_WALL_FAN:
            case DEAD_BRAIN_CORAL_FAN:
            case DEAD_BRAIN_CORAL_WALL_FAN:
            case DEAD_BUBBLE_CORAL_FAN:
            case DEAD_FIRE_CORAL_FAN:
            case DEAD_BUBBLE_CORAL_WALL_FAN:
            case DEAD_FIRE_CORAL_WALL_FAN:
            case DEAD_HORN_CORAL_FAN:
            case DEAD_HORN_CORAL_WALL_FAN:
            case DEAD_TUBE_CORAL_FAN:
            case DEAD_TUBE_CORAL_WALL_FAN:
            case HORN_CORAL_FAN:
            case HORN_CORAL_WALL_FAN:
            case TUBE_CORAL_FAN:
            case TUBE_CORAL_WALL_FAN:
            case TNT:
            case CRACKED_POLISHED_BLACKSTONE_BRICKS:
            case CRACKED_STONE_BRICKS:
            case CRACKED_NETHER_BRICKS:
            case CRACKED_DEEPSLATE_TILES:
            case DEEPSLATE_TILES:
            case DEEPSLATE_TILE_SLAB:
            case DEEPSLATE_TILE_WALL:
            case DEEPSLATE_TILE_STAIRS:
            case COBBLED_DEEPSLATE:
            case CHISELED_DEEPSLATE:
            case INFESTED_DEEPSLATE:
            case REINFORCED_DEEPSLATE:
            case COBBLED_DEEPSLATE_SLAB:
            case COBBLED_DEEPSLATE_WALL:
            case COBBLED_DEEPSLATE_STAIRS:
            case CRACKED_DEEPSLATE_BRICKS:
            case INFESTED_CRACKED_STONE_BRICKS:
            case END_STONE_BRICKS:
            case END_STONE_BRICK_SLAB:
            case END_STONE_BRICK_WALL:
            case END_STONE_BRICK_STAIRS:
            case STONE_STAIRS:
            case STONE_PRESSURE_PLATE:
            case INFESTED_STONE:
            case BUBBLE_COLUMN:
                return Tools.PICKAXE;
            default:
                return Tools.NONE;
        }

    }
}
