package me.marcangeloh.API.Util.ConfigurationUtil;

import me.marcangeloh.API.Util.GeneralUtil.Tools;
import org.bukkit.Material;

public class ToolUtil {

    public static Tools getToolTypeFromString(String tool) {
        switch (tool.toLowerCase()) {
            case "armor":
            case "chestplate":
            case "leggings":
            case "boots":
            case "helmet":
            case "elytra":
                return Tools.ARMOR;
            case "shovel":
            case "spade":
                return Tools.SHOVEL;
            case "pickaxe":
            case "pick":
                return Tools.PICKAXE;
            case "hoe":
            case "till":
                return Tools.HOE;
            case "fishing_rod":
            case "fish_rod":
            case "fishing":
            case "fishing rod":
            case "fish rod":
            case "fish":
                return Tools.FISH_ROD;
            case "axe":
                return Tools.AXE;
            case "bow":
            case "ranged_weapon":
            case "ranged":
            case "arrow":
            case "trident":
            case "crossbow":
            case "trid":
            case "crossb":
                return Tools.RANGED_WEAPON;
            case "sword":
            case "swords":
            case "melee_weapon":
                return Tools.MELEE_WEAPON;
            default:
                return Tools.NONE;
        }
    }

    public static Tools getToolTypeForMaterial(Material material) {
        switch (material) {
            case BAMBOO_STAIRS:
            case BAMBOO:
            case BAMBOO_BLOCK:
            case BAMBOO_BUTTON:
            case BAMBOO_CHEST_RAFT:
            case BAMBOO_DOOR:
            case BAMBOO_FENCE:
            case BAMBOO_FENCE_GATE:
            case BAMBOO_HANGING_SIGN:
            case BAMBOO_MOSAIC:
            case BAMBOO_MOSAIC_SLAB:
            case BAMBOO_MOSAIC_STAIRS:
            case BAMBOO_PLANKS:
            case BAMBOO_PRESSURE_PLATE:
            case BAMBOO_RAFT:
            case BAMBOO_SLAB:
            case BAMBOO_TRAPDOOR:
            case BAMBOO_SIGN:
            case BAMBOO_WALL_HANGING_SIGN:
            case BAMBOO_WALL_SIGN:
            case OAK_BOAT:
            case OAK_BUTTON:
            case OAK_CHEST_BOAT:
            case OAK_DOOR:
            case OAK_FENCE:
            case OAK_FENCE_GATE:
            case OAK_HANGING_SIGN:
            case OAK_LOG:
            case OAK_PLANKS:
            case OAK_PRESSURE_PLATE:
            case OAK_SIGN:
            case OAK_SLAB:
            case OAK_STAIRS:
            case OAK_TRAPDOOR:
            case OAK_WALL_SIGN:
            case OAK_WOOD:
            case OAK_WALL_HANGING_SIGN:
            case DARK_OAK_BOAT:
            case DARK_OAK_BUTTON:
            case DARK_OAK_CHEST_BOAT:
            case DARK_OAK_DOOR:
            case DARK_OAK_FENCE:
            case DARK_OAK_FENCE_GATE:
            case DARK_OAK_HANGING_SIGN:
            case DARK_OAK_LOG:
            case DARK_OAK_PLANKS:
            case DARK_OAK_PRESSURE_PLATE:
            case DARK_OAK_SIGN:
            case DARK_OAK_SLAB:
            case DARK_OAK_STAIRS:
            case DARK_OAK_TRAPDOOR:
            case DARK_OAK_WALL_HANGING_SIGN:
            case DARK_OAK_WALL_SIGN:
            case DARK_OAK_WOOD:
            case JUNGLE_BOAT:
            case JUNGLE_BUTTON:
            case JUNGLE_CHEST_BOAT:
            case JUNGLE_DOOR:
            case JUNGLE_FENCE:
            case JUNGLE_FENCE_GATE:
            case JUNGLE_HANGING_SIGN:
            case JUNGLE_LOG:
            case JUNGLE_PLANKS:
            case JUNGLE_SIGN:
            case JUNGLE_PRESSURE_PLATE:
            case JUNGLE_SLAB:
            case JUNGLE_STAIRS:
            case JUNGLE_TRAPDOOR:
            case JUNGLE_WOOD:
            case JUNGLE_WALL_HANGING_SIGN:
            case JUNGLE_WALL_SIGN:
            case BIRCH_BOAT:
            case BIRCH_BUTTON:
            case BIRCH_CHEST_BOAT:
            case BIRCH_DOOR:
            case BIRCH_FENCE:
            case BIRCH_FENCE_GATE:
            case BIRCH_HANGING_SIGN:
            case BIRCH_LOG:
            case BIRCH_PLANKS:
            case BIRCH_PRESSURE_PLATE:
            case BIRCH_SIGN:
            case BIRCH_SLAB:
            case BIRCH_STAIRS:
            case BIRCH_TRAPDOOR:
            case BIRCH_WOOD:
            case BIRCH_WALL_HANGING_SIGN:
            case BIRCH_WALL_SIGN:
            case ACACIA_LOG:
            case ACACIA_BOAT:
            case ACACIA_BUTTON:
            case ACACIA_CHEST_BOAT:
            case ACACIA_DOOR:
            case ACACIA_FENCE:
            case ACACIA_FENCE_GATE:
            case ACACIA_HANGING_SIGN:
            case ACACIA_PLANKS:
            case ACACIA_PRESSURE_PLATE:
            case ACACIA_SIGN:
            case ACACIA_SLAB:
            case ACACIA_STAIRS:
            case ACACIA_TRAPDOOR:
            case ACACIA_WOOD:
            case ACACIA_WALL_HANGING_SIGN:
            case ACACIA_WALL_SIGN:
            case MANGROVE_LOG:
            case MANGROVE_BOAT:
            case MANGROVE_BUTTON:
            case MANGROVE_CHEST_BOAT:
            case MANGROVE_DOOR:
            case MANGROVE_FENCE:
            case MANGROVE_FENCE_GATE:
            case MANGROVE_HANGING_SIGN:
            case MANGROVE_PLANKS:
            case MANGROVE_PROPAGULE:
            case MANGROVE_ROOTS:
            case MANGROVE_SIGN:
            case MANGROVE_SLAB:
            case MANGROVE_STAIRS:
            case MANGROVE_TRAPDOOR:
            case MANGROVE_PRESSURE_PLATE:
            case MANGROVE_WALL_SIGN:
            case MANGROVE_WOOD:
            case MANGROVE_WALL_HANGING_SIGN:
            case SPRUCE_LOG:
            case SPRUCE_BOAT:
            case SPRUCE_BUTTON:
            case SPRUCE_CHEST_BOAT:
            case SPRUCE_DOOR:
            case SPRUCE_FENCE:
            case SPRUCE_FENCE_GATE:
            case SPRUCE_HANGING_SIGN:
            case SPRUCE_PLANKS:
            case SPRUCE_PRESSURE_PLATE:
            case SPRUCE_SIGN:
            case SPRUCE_SLAB:
            case SPRUCE_STAIRS:
            case SPRUCE_TRAPDOOR:
            case SPRUCE_WOOD:
            case SPRUCE_WALL_HANGING_SIGN:
            case SPRUCE_WALL_SIGN:
            case CHEST:
            case CRAFTING_TABLE:
            case STRIPPED_ACACIA_LOG:
            case STRIPPED_ACACIA_WOOD:
            case STRIPPED_BAMBOO_BLOCK:
            case STRIPPED_BIRCH_LOG:
            case STRIPPED_BIRCH_WOOD:
            case STRIPPED_CRIMSON_HYPHAE:
            case CRIMSON_HYPHAE:
            case CRIMSON_BUTTON:
            case CRIMSON_DOOR:
            case CRIMSON_FENCE:
            case CRIMSON_FENCE_GATE:
            case CRIMSON_HANGING_SIGN:
            case CRIMSON_PLANKS:
            case CRIMSON_ROOTS:
            case CRIMSON_PRESSURE_PLATE:
            case CRIMSON_SIGN:
            case CRIMSON_SLAB:
            case CRIMSON_STAIRS:
            case CRIMSON_STEM:
            case CRIMSON_TRAPDOOR:
            case CRIMSON_WALL_HANGING_SIGN:
            case CRIMSON_WALL_SIGN:
            case TRAPPED_CHEST:
            case WARPED_BUTTON:
            case WARPED_DOOR:
            case WARPED_FENCE:
            case WARPED_FENCE_GATE:
            case WARPED_PLANKS:
            case WARPED_PRESSURE_PLATE:
            case WARPED_ROOTS:
            case WARPED_STAIRS:
            case WARPED_SIGN:
            case WARPED_HANGING_SIGN:
            case WARPED_TRAPDOOR:
            case WARPED_WALL_HANGING_SIGN:
            case WARPED_WALL_SIGN:
            case WARPED_SLAB:
            case JUKEBOX:
            case NOTE_BLOCK:
            case FLETCHING_TABLE:
            case CARTOGRAPHY_TABLE:
            case BOOKSHELF:
            case CHISELED_BOOKSHELF:
            case LECTERN:
            case BAMBOO_SAPLING:
            case OAK_LEAVES:
            case SPRUCE_LEAVES:
            case OAK_SAPLING:
            case SPRUCE_SAPLING:
            case DARK_OAK_LEAVES:
            case DARK_OAK_SAPLING:
            case BIRCH_SAPLING:
            case BIRCH_LEAVES:
            case ACACIA_LEAVES:
            case ACACIA_SAPLING:
            case JUNGLE_SAPLING:
            case JUNGLE_LEAVES:
            case POTTED_ACACIA_SAPLING:
            case POTTED_BIRCH_SAPLING:
            case POTTED_DARK_OAK_SAPLING:
            case POTTED_JUNGLE_SAPLING:
            case POTTED_OAK_SAPLING:
            case POTTED_SPRUCE_SAPLING:
            case PLAYER_HEAD:
            case PLAYER_WALL_HEAD:
            case CAVE_VINES:
            case CAVE_VINES_PLANT:
            case CHARCOAL:
            case AZALEA_LEAVES:
            case FLOWERING_AZALEA_LEAVES:
            case MANGROVE_LEAVES:
            case AZALEA:
            case POTTED_FLOWERING_AZALEA_BUSH:
            case POTTED_BAMBOO:
            case POTTED_WARPED_ROOTS:
            case WARPED_STEM:
            case POTTED_CRIMSON_ROOTS:
            case WARPED_HYPHAE:
            case STRIPPED_CRIMSON_STEM:
            case STRIPPED_DARK_OAK_LOG:
            case STRIPPED_DARK_OAK_WOOD:
            case STRIPPED_JUNGLE_LOG:
            case STRIPPED_JUNGLE_WOOD:
            case STRIPPED_MANGROVE_LOG:
            case STRIPPED_MANGROVE_WOOD:
            case STRIPPED_OAK_LOG:
            case STRIPPED_OAK_WOOD:
            case STRIPPED_SPRUCE_LOG:
            case STRIPPED_SPRUCE_WOOD:
            case STRIPPED_WARPED_HYPHAE:
            case STRIPPED_WARPED_STEM:
            case POTTED_MANGROVE_PROPAGULE:
            case STICK:
            case CARROT_ON_A_STICK:
            case CAMPFIRE:
            case SOUL_CAMPFIRE:
            case LOOM:
            case COMPOSTER:
            case BARREL:
            case ZOMBIE_HEAD:
            case SKELETON_SKULL:
            case ZOMBIE_WALL_HEAD:
            case DRAGON_HEAD:
            case DRAGON_WALL_HEAD:
            case CREEPER_HEAD:
            case CREEPER_WALL_HEAD:
            case PIGLIN_HEAD:
            case PIGLIN_WALL_HEAD:
            case PISTON_HEAD:
            case SKELETON_WALL_SKULL:
            case WITHER_SKELETON_SKULL:
            case WITHER_SKELETON_WALL_SKULL:
            case LADDER:
            case BLACK_BED:
            case BLUE_BED:
            case BROWN_BED:
            case CYAN_BED:
            case GRAY_BED:
            case GREEN_BED:
            case LIGHT_BLUE_BED:
            case LIGHT_GRAY_BED:
            case LIME_BED:
            case MAGENTA_BED:
            case ORANGE_BED:
            case PINK_BED:
            case PURPLE_BED:
            case RED_BED:
            case WHITE_BED:
            case YELLOW_BED:
            case PAINTING:
            case BLACK_BANNER:
            case BLACK_WALL_BANNER:
            case BLUE_BANNER:
            case BLUE_WALL_BANNER:
            case BROWN_BANNER:
            case BROWN_WALL_BANNER:
            case CREEPER_BANNER_PATTERN:
            case CYAN_BANNER:
            case CYAN_WALL_BANNER:
            case FLOWER_BANNER_PATTERN:
            case GLOBE_BANNER_PATTERN:
            case GRAY_BANNER:
            case GRAY_WALL_BANNER:
            case GREEN_BANNER:
            case GREEN_WALL_BANNER:
            case LIGHT_BLUE_BANNER:
            case LIGHT_BLUE_WALL_BANNER:
            case LIGHT_GRAY_BANNER:
            case RED_BANNER:
            case LIGHT_GRAY_WALL_BANNER:
            case LIME_BANNER:
            case LIME_WALL_BANNER:
            case MAGENTA_BANNER:
            case MAGENTA_WALL_BANNER:
            case MOJANG_BANNER_PATTERN:
            case ORANGE_BANNER:
            case ORANGE_WALL_BANNER:
            case PIGLIN_BANNER_PATTERN:
            case PINK_BANNER:
            case PINK_WALL_BANNER:
            case PURPLE_BANNER:
            case PURPLE_WALL_BANNER:
            case RED_WALL_BANNER:
            case SKULL_BANNER_PATTERN:
            case WHITE_BANNER:
            case WHITE_WALL_BANNER:
            case YELLOW_BANNER:
            case YELLOW_WALL_BANNER:
            case BLACK_CARPET:
            case BLUE_CARPET:
            case BROWN_CARPET:
            case CYAN_CARPET:
            case GRAY_CARPET:
            case GREEN_CARPET:
            case LIGHT_BLUE_CARPET:
            case LIGHT_GRAY_CARPET:
            case LIME_CARPET:
            case MAGENTA_CARPET:
            case MOSS_CARPET:
            case ORANGE_CARPET:
            case PINK_CARPET:
            case PURPLE_CARPET:
            case RED_CARPET:
            case WHITE_CARPET:
            case YELLOW_CARPET:
            case ITEM_FRAME:
            case SCAFFOLDING:
            case GLOW_ITEM_FRAME:
            case CARVED_PUMPKIN:
            case JACK_O_LANTERN:
            case SMITHING_TABLE:
                return Tools.AXE;
            case DIRT:
            case DIRT_PATH:
            case COARSE_DIRT:
            case ROOTED_DIRT:
            case GRASS_BLOCK:
            case SNOW_BLOCK:
            case POWDER_SNOW:
            case SNOW:
            case SAND:
            case SOUL_SAND:
            case GRAVEL:
            case RED_SAND:
            case MYCELIUM:
            case FARMLAND:
            case MUD:
            case MUDDY_MANGROVE_ROOTS:
            case BLACK_CONCRETE_POWDER:
            case BLUE_CONCRETE_POWDER:
            case PINK_CONCRETE_POWDER:
            case BROWN_CONCRETE_POWDER:
            case CYAN_CONCRETE_POWDER:
            case GRAY_CONCRETE_POWDER:
            case GREEN_CONCRETE_POWDER:
            case LIGHT_BLUE_CONCRETE_POWDER:
            case LIGHT_GRAY_CONCRETE_POWDER:
            case LIME_CONCRETE_POWDER:
            case MAGENTA_CONCRETE_POWDER:
            case ORANGE_CONCRETE_POWDER:
            case PURPLE_CONCRETE_POWDER:
            case RED_CONCRETE_POWDER:
            case WHITE_CONCRETE_POWDER:
            case YELLOW_CONCRETE_POWDER:
            case SOUL_SOIL:
            case PODZOL:
            case CLAY:
            case GRASS:
            case GLASS:
            case GLASS_BOTTLE:
            case GLASS_PANE:
            case GRAY_STAINED_GLASS:
            case GREEN_STAINED_GLASS:
            case BLUE_STAINED_GLASS:
            case BLACK_STAINED_GLASS:
            case CYAN_STAINED_GLASS:
            case SPYGLASS:
            case BROWN_STAINED_GLASS:
            case LIGHT_GRAY_STAINED_GLASS:
            case YELLOW_STAINED_GLASS_PANE:
            case LIME_STAINED_GLASS:
            case MAGENTA_STAINED_GLASS:
            case ORANGE_STAINED_GLASS:
            case TINTED_GLASS:
            case LIGHT_BLUE_STAINED_GLASS:
            case PINK_STAINED_GLASS:
            case GRAY_STAINED_GLASS_PANE:
            case PURPLE_STAINED_GLASS:
            case RED_STAINED_GLASS:
            case WHITE_STAINED_GLASS:
            case YELLOW_STAINED_GLASS:
            case GREEN_STAINED_GLASS_PANE:
            case BLACK_STAINED_GLASS_PANE:
            case BLUE_STAINED_GLASS_PANE:
            case BROWN_STAINED_GLASS_PANE:
            case PINK_STAINED_GLASS_PANE:
            case PURPLE_STAINED_GLASS_PANE:
            case CYAN_STAINED_GLASS_PANE:
            case LIGHT_BLUE_STAINED_GLASS_PANE:
            case LIGHT_GRAY_STAINED_GLASS_PANE:
            case LIME_STAINED_GLASS_PANE:
            case MAGENTA_STAINED_GLASS_PANE:
            case ORANGE_STAINED_GLASS_PANE:
            case RED_STAINED_GLASS_PANE:
            case WHITE_STAINED_GLASS_PANE:
            case FLINT:
            case FLINT_AND_STEEL:
            case SNOWBALL:
            case POWDER_SNOW_BUCKET:
            case CLAY_BALL:
                return Tools.SHOVEL;
            case LAVA_CAULDRON:
            case WATER_CAULDRON:
            case POWDER_SNOW_CAULDRON:
            case BOWL:
            case CHAIN:
            case CLOCK:
            case COMPASS:
            case COMPARATOR:
            case SOUL_LANTERN:
            case TORCH:
            case REDSTONE:
            case REDSTONE_LAMP:
            case REDSTONE_TORCH:
            case REDSTONE_WALL_TORCH:
            case REDSTONE_WIRE:
            case HEAVY_WEIGHTED_PRESSURE_PLATE:
            case LIGHT_WEIGHTED_PRESSURE_PLATE:
            case PISTON:
            case STICKY_PISTON:
            case STONE_BUTTON:
            case OBSIDIAN:
            case ANCIENT_DEBRIS:
            case CRYING_OBSIDIAN:
            case RESPAWN_ANCHOR:
            case ENDER_CHEST:
            case ANVIL:
            case COAL_BLOCK:
            case DIAMOND_BLOCK:
            case NETHERITE_BLOCK:
            case EMERALD_BLOCK:
            case IRON_BLOCK:
            case REDSTONE_BLOCK:
            case GOLD_BLOCK:
            case ENCHANTING_TABLE:
            case IRON_BARS:
            case IRON_DOOR:
            case IRON_TRAPDOOR:
            case SPAWNER:
            case BELL:
            case DISPENSER:
            case DROPPER:
            case OBSERVER:
            case FURNACE:
            case BLAST_FURNACE:
            case SMOKER:
            case STONECUTTER:
            case LODESTONE:
            case LANTERN:
            case CONDUIT:
            case COAL_ORE:
            case DRAGON_EGG:
            case DIAMOND_ORE:
            case EMERALD_ORE:
            case END_STONE:
            case GOLD_ORE:
            case HOPPER:
            case IRON_ORE:
            case LAPIS_BLOCK:
            case LAPIS_ORE:
            case NETHER_QUARTZ_ORE:
            case NETHER_GOLD_ORE:
            case REDSTONE_ORE:
            case GRINDSTONE:
            case BONE_BLOCK:
            case BRICK_STAIRS:
            case BRICKS:
            case BRICK_SLAB:
            case BRICK_WALL:
            case CAULDRON:
            case TUFF:
            case COBBLESTONE:
            case COBBLESTONE_SLAB:
            case COBBLESTONE_WALL:
            case COBBLESTONE_STAIRS:
            case MOSSY_COBBLESTONE:
            case NETHER_BRICKS:
            case RED_NETHER_BRICKS:
            case NETHER_BRICK_FENCE:
            case NETHER_BRICK_STAIRS:
            case STONE_SLAB:
            case POLISHED_BLACKSTONE:
            case RED_CONCRETE:
            case BLACK_CONCRETE:
            case BLUE_CONCRETE:
            case CYAN_CONCRETE:
            case BROWN_CONCRETE:
            case GRAY_CONCRETE:
            case GREEN_CONCRETE:
            case LIGHT_BLUE_CONCRETE:
            case LIGHT_GRAY_CONCRETE:
            case LIME_CONCRETE:
            case MAGENTA_CONCRETE:
            case ORANGE_CONCRETE:
            case PINK_CONCRETE:
            case PURPLE_CONCRETE:
            case WHITE_CONCRETE:
            case YELLOW_CONCRETE:
            case SHULKER_BOX:
            case ANDESITE:
            case ANDESITE_SLAB:
            case ANDESITE_WALL:
            case ANDESITE_STAIRS:
            case DARK_PRISMARINE:
            case DIORITE:
            case DIORITE_SLAB:
            case DIORITE_WALL:
            case DIORITE_STAIRS:
            case GRANITE:
            case GRANITE_SLAB:
            case GRANITE_WALL:
            case GRANITE_STAIRS:
            case POLISHED_GRANITE:
            case PRISMARINE:
            case PRISMARINE_SLAB:
            case PRISMARINE_STAIRS:
            case PRISMARINE_BRICK_SLAB:
            case PRISMARINE_BRICK_STAIRS:
            case PRISMARINE_BRICKS:
            case STONE:
            case SMOOTH_SANDSTONE:
            case SMOOTH_STONE:
            case PURPUR_BLOCK:
            case PURPUR_PILLAR:
            case PURPUR_SLAB:
            case PURPUR_STAIRS:
            case SANDSTONE:
            case SANDSTONE_SLAB:
            case SANDSTONE_STAIRS:
            case SANDSTONE_WALL:
            case SMOOTH_RED_SANDSTONE:
            case STONE_BRICK_SLAB:
            case STONE_BRICK_STAIRS:
            case STONE_BRICK_WALL:
            case STONE_BRICKS:
            case BLACKSTONE:
            case BLACKSTONE_SLAB:
            case BLACKSTONE_STAIRS:
            case BLACKSTONE_WALL:
            case BLACK_SHULKER_BOX:
            case BLUE_SHULKER_BOX:
            case BROWN_SHULKER_BOX:
            case CYAN_SHULKER_BOX:
            case GRAY_SHULKER_BOX:
            case GREEN_SHULKER_BOX:
            case LIGHT_BLUE_SHULKER_BOX:
            case LIME_SHULKER_BOX:
            case MAGENTA_SHULKER_BOX:
            case ORANGE_SHULKER_BOX:
            case PINK_SHULKER_BOX:
            case PURPLE_SHULKER_BOX:
            case RED_SHULKER_BOX:
            case WHITE_SHULKER_BOX:
            case YELLOW_SHULKER_BOX:
            case LIGHT_GRAY_SHULKER_BOX:
            case CHISELED_POLISHED_BLACKSTONE:
            case CHISELED_STONE_BRICKS:
            case POLISHED_ANDESITE:
            case POLISHED_ANDESITE_SLAB:
            case POLISHED_ANDESITE_STAIRS:
            case POLISHED_BASALT:
            case POLISHED_BLACKSTONE_BRICK_SLAB:
            case POLISHED_BLACKSTONE_BRICK_STAIRS:
            case POLISHED_BLACKSTONE_BRICK_WALL:
            case POLISHED_BLACKSTONE_BRICKS:
            case POLISHED_BLACKSTONE_BUTTON:
            case POLISHED_BLACKSTONE_PRESSURE_PLATE:
            case POLISHED_BLACKSTONE_SLAB:
            case POLISHED_BLACKSTONE_STAIRS:
            case POLISHED_BLACKSTONE_WALL:
            case POLISHED_DEEPSLATE:
            case POLISHED_DEEPSLATE_SLAB:
            case POLISHED_DEEPSLATE_STAIRS:
            case POLISHED_DIORITE:
            case POLISHED_DIORITE_SLAB:
            case POLISHED_DIORITE_STAIRS:
            case POLISHED_DEEPSLATE_WALL:
            case POLISHED_GRANITE_SLAB:
            case POLISHED_GRANITE_STAIRS:
            case GILDED_BLACKSTONE:
            case BLACK_GLAZED_TERRACOTTA:
            case GRAY_GLAZED_TERRACOTTA:
            case RED_GLAZED_TERRACOTTA:
            case BLUE_GLAZED_TERRACOTTA:
            case CYAN_GLAZED_TERRACOTTA:
            case LIME_GLAZED_TERRACOTTA:
            case PINK_GLAZED_TERRACOTTA:
            case BROWN_GLAZED_TERRACOTTA:
            case GREEN_GLAZED_TERRACOTTA:
            case WHITE_GLAZED_TERRACOTTA:
            case ORANGE_GLAZED_TERRACOTTA:
            case PURPLE_GLAZED_TERRACOTTA:
            case YELLOW_GLAZED_TERRACOTTA:
            case MAGENTA_GLAZED_TERRACOTTA:
            case LIGHT_BLUE_GLAZED_TERRACOTTA:
            case LIGHT_GRAY_GLAZED_TERRACOTTA:
            case TERRACOTTA:
            case RED_TERRACOTTA:
            case BLUE_TERRACOTTA:
            case CYAN_TERRACOTTA:
            case GRAY_TERRACOTTA:
            case LIME_TERRACOTTA:
            case PINK_TERRACOTTA:
            case BLACK_TERRACOTTA:
            case BROWN_TERRACOTTA:
            case GREEN_TERRACOTTA:
            case WHITE_TERRACOTTA:
            case ORANGE_TERRACOTTA:
            case PURPLE_TERRACOTTA:
            case YELLOW_TERRACOTTA:
            case MAGENTA_TERRACOTTA:
            case LIGHT_BLUE_TERRACOTTA:
            case LIGHT_GRAY_TERRACOTTA:
            case BASALT:
            case SMOOTH_BASALT:
            case QUARTZ:
            case QUARTZ_BLOCK:
            case QUARTZ_BRICKS:
            case QUARTZ_PILLAR:
            case QUARTZ_SLAB:
            case QUARTZ_STAIRS:
            case CHISELED_QUARTZ_BLOCK:
            case SMOOTH_QUARTZ:
            case SMOOTH_QUARTZ_SLAB:
            case SMOOTH_QUARTZ_STAIRS:
            case RED_SANDSTONE:
            case RED_SANDSTONE_SLAB:
            case RED_SANDSTONE_WALL:
            case RED_SANDSTONE_STAIRS:
            case CUT_RED_SANDSTONE:
            case CHISELED_RED_SANDSTONE:
            case CUT_RED_SANDSTONE_SLAB:
            case SMOOTH_RED_SANDSTONE_SLAB:
            case SMOOTH_RED_SANDSTONE_STAIRS:
            case CUT_SANDSTONE:
            case CHISELED_SANDSTONE:
            case SMOOTH_SANDSTONE_SLAB:
            case SMOOTH_SANDSTONE_STAIRS:
            case CUT_SANDSTONE_SLAB:
            case WARPED_NYLIUM:
            case CRIMSON_NYLIUM:
            case RAIL:
            case POWERED_RAIL:
            case DETECTOR_RAIL:
            case ACTIVATOR_RAIL:
            case BREWING_STAND:
            case BLUE_ICE:
            case ICE:
            case MAGMA_BLOCK:
            case PACKED_ICE:
            case FROSTED_ICE:
            case NETHERRACK:
            case END_ROD:
            case DEEPSLATE:
            case DEEPSLATE_BRICK_SLAB:
            case DEEPSLATE_BRICK_STAIRS:
            case DEEPSLATE_BRICK_WALL:
            case DEEPSLATE_BRICKS:
            case DEEPSLATE_COAL_ORE:
            case DEEPSLATE_COPPER_ORE:
            case DEEPSLATE_DIAMOND_ORE:
            case COPPER_BLOCK:
            case COPPER_ORE:
            case CUT_COPPER:
            case CUT_COPPER_SLAB:
            case CUT_COPPER_STAIRS:
            case EXPOSED_CUT_COPPER:
            case EXPOSED_COPPER:
            case RAW_COPPER_BLOCK:
            case WAXED_CUT_COPPER:
            case WAXED_CUT_COPPER_SLAB:
            case WAXED_CUT_COPPER_STAIRS:
            case WAXED_EXPOSED_COPPER:
            case WAXED_EXPOSED_CUT_COPPER:
            case WAXED_EXPOSED_CUT_COPPER_SLAB:
            case WAXED_OXIDIZED_CUT_COPPER:
            case OXIDIZED_COPPER:
            case OXIDIZED_CUT_COPPER:
            case OXIDIZED_CUT_COPPER_SLAB:
            case OXIDIZED_CUT_COPPER_STAIRS:
            case WAXED_COPPER_BLOCK:
            case WAXED_OXIDIZED_COPPER:
            case WAXED_EXPOSED_CUT_COPPER_STAIRS:
            case WAXED_OXIDIZED_CUT_COPPER_SLAB:
            case WAXED_OXIDIZED_CUT_COPPER_STAIRS:
            case WAXED_WEATHERED_COPPER:
            case WAXED_WEATHERED_CUT_COPPER:
            case WAXED_WEATHERED_CUT_COPPER_SLAB:
            case WAXED_WEATHERED_CUT_COPPER_STAIRS:
            case WEATHERED_COPPER:
            case WEATHERED_CUT_COPPER:
            case WEATHERED_CUT_COPPER_SLAB:
            case WEATHERED_CUT_COPPER_STAIRS:
            case DEEPSLATE_GOLD_ORE:
            case DEEPSLATE_EMERALD_ORE:
            case DEEPSLATE_IRON_ORE:
            case DEEPSLATE_LAPIS_ORE:
            case DEEPSLATE_REDSTONE_ORE:
            case BRAIN_CORAL_BLOCK:
            case BUBBLE_CORAL_BLOCK:
            case AMETHYST_BLOCK:
            case DRIPSTONE_BLOCK:
            case DEAD_BRAIN_CORAL_BLOCK:
            case DEAD_BUBBLE_CORAL_BLOCK:
            case DEAD_FIRE_CORAL_BLOCK:
            case BRAIN_CORAL:
            case BUBBLE_CORAL:
            case DEAD_BRAIN_CORAL:
            case DEAD_BUBBLE_CORAL:
            case DEAD_FIRE_CORAL:
            case DEAD_HORN_CORAL:
            case DEAD_TUBE_CORAL:
            case FIRE_CORAL:
            case HORN_CORAL:
            case TUBE_CORAL:
            case BRAIN_CORAL_FAN:
            case BUBBLE_CORAL_FAN:
            case BRAIN_CORAL_WALL_FAN:
            case FIRE_CORAL_FAN:
            case FIRE_CORAL_WALL_FAN:
            case BUBBLE_CORAL_WALL_FAN:
            case DEAD_BRAIN_CORAL_FAN:
            case DEAD_BRAIN_CORAL_WALL_FAN:
            case DEAD_BUBBLE_CORAL_FAN:
            case DEAD_FIRE_CORAL_FAN:
            case DEAD_BUBBLE_CORAL_WALL_FAN:
            case DEAD_FIRE_CORAL_WALL_FAN:
            case DEAD_HORN_CORAL_FAN:
            case DEAD_HORN_CORAL_WALL_FAN:
            case DEAD_TUBE_CORAL_FAN:
            case DEAD_TUBE_CORAL_WALL_FAN:
            case HORN_CORAL_FAN:
            case HORN_CORAL_WALL_FAN:
            case TUBE_CORAL_FAN:
            case TUBE_CORAL_WALL_FAN:
            case TNT:
            case CRACKED_POLISHED_BLACKSTONE_BRICKS:
            case CRACKED_STONE_BRICKS:
            case CRACKED_NETHER_BRICKS:
            case CRACKED_DEEPSLATE_TILES:
            case DEEPSLATE_TILES:
            case DEEPSLATE_TILE_SLAB:
            case DEEPSLATE_TILE_WALL:
            case DEEPSLATE_TILE_STAIRS:
            case COBBLED_DEEPSLATE:
            case CHISELED_DEEPSLATE:
            case INFESTED_DEEPSLATE:
            case REINFORCED_DEEPSLATE:
            case COBBLED_DEEPSLATE_SLAB:
            case COBBLED_DEEPSLATE_WALL:
            case COBBLED_DEEPSLATE_STAIRS:
            case CRACKED_DEEPSLATE_BRICKS:
            case INFESTED_CRACKED_STONE_BRICKS:
            case END_STONE_BRICKS:
            case END_STONE_BRICK_SLAB:
            case END_STONE_BRICK_WALL:
            case END_STONE_BRICK_STAIRS:
            case STONE_STAIRS:
            case STONE_PRESSURE_PLATE:
            case INFESTED_STONE:
            case BUBBLE_COLUMN:
            case DARK_PRISMARINE_SLAB:
            case DARK_PRISMARINE_STAIRS:
            case PRISMARINE_CRYSTALS:
            case PRISMARINE_SHARD:
            case PRISMARINE_WALL:
            case COAL:
            case DEAD_HORN_CORAL_BLOCK:
            case DEAD_TUBE_CORAL_BLOCK:
            case GLOWSTONE:
            case GLOWSTONE_DUST:
            case NETHER_BRICK:
            case NETHER_BRICK_SLAB:
            case NETHER_BRICK_WALL:
            case NETHER_STAR:
            case NETHERITE_INGOT:
            case NETHERITE_SCRAP:
            case POINTED_DRIPSTONE:
            case GOLD_INGOT:
            case GOLD_NUGGET:
            case IRON_INGOT:
            case IRON_NUGGET:
            case IRON_HORSE_ARMOR:
            case DIAMOND_HORSE_ARMOR:
            case GOLDEN_HORSE_ARMOR:
            case LEATHER_HORSE_ARMOR:
            case BRICK:
            case MINECART:
            case CHEST_MINECART:
            case FURNACE_MINECART:
            case HOPPER_MINECART:
            case TNT_MINECART:
            case BEACON:
            case LEVER:
            case EMERALD:
            case CALCITE:
            case AMETHYST_CLUSTER:
            case AMETHYST_SHARD:
            case BUDDING_AMETHYST:
            case LARGE_AMETHYST_BUD:
            case SMALL_AMETHYST_BUD:
            case MEDIUM_AMETHYST_BUD:
            case DIAMOND:
            case REPEATER:
            case TRIPWIRE:
            case RAW_COPPER:
            case RAW_GOLD:
            case RAW_GOLD_BLOCK:
            case RAW_IRON:
            case RAW_IRON_BLOCK:
            case RED_NETHER_BRICK_SLAB:
            case RED_NETHER_BRICK_STAIRS:
            case RED_NETHER_BRICK_WALL:
            case SOUL_TORCH:
            case SOUL_WALL_TORCH:
            case WALL_TORCH:
            case DAYLIGHT_DETECTOR:
            case CHIPPED_ANVIL:
            case DAMAGED_ANVIL:
            case MOSSY_COBBLESTONE_SLAB:
            case MOSSY_COBBLESTONE_STAIRS:
            case MOSSY_COBBLESTONE_WALL:
            case MOSSY_STONE_BRICK_SLAB:
            case MOSSY_STONE_BRICK_STAIRS:
            case MOSSY_STONE_BRICK_WALL:
            case MOSSY_STONE_BRICKS:
            case INFESTED_MOSSY_STONE_BRICKS:
            case MUD_BRICK_SLAB:
            case MUD_BRICK_STAIRS:
            case MUD_BRICKS:
            case MUD_BRICK_WALL:
            case PACKED_MUD:
            case LAVA_BUCKET:
            case ARMOR_STAND:
            case FIRE_CORAL_BLOCK:
            case COPPER_INGOT:
            case FLOWER_POT:
            case SEA_LANTERN:
            case LAPIS_LAZULI:
            case LIGHTNING_ROD:
            case TRIPWIRE_HOOK:
            case PETRIFIED_OAK_SLAB:
            case TUBE_CORAL_BLOCK:
            case HORN_CORAL_BLOCK:
            case SMOOTH_STONE_SLAB:
            case EXPOSED_CUT_COPPER_SLAB:
            case INFESTED_COBBLESTONE:
            case INFESTED_CHISELED_STONE_BRICKS:
            case INFESTED_STONE_BRICKS:
                return Tools.PICKAXE;
            case GLISTERING_MELON_SLICE:
            case POISONOUS_POTATO:
            case SWEET_BERRIES:
            case SWEET_BERRY_BUSH:
            case RECOVERY_COMPASS:
            case SUGAR:
            case SUGAR_CANE:
            case PAPER:
            case FLOWERING_AZALEA:
            case WHEAT:
            case WHEAT_SEEDS:
            case POTATO:
            case POTATOES:
            case CARROT:
            case CARROTS:
            case BEETROOT:
            case BEETROOT_SEEDS:
            case BEETROOT_SOUP:
            case BEETROOTS:
            case HAY_BLOCK:
            case BONE_MEAL:
            case PUMPKIN:
            case MELON:
            case MELON_SEEDS:
            case MELON_SLICE:
            case PUMPKIN_PIE:
            case PUMPKIN_SEEDS:
            case PUMPKIN_STEM:
            case MELON_STEM:
            case MUSHROOM_STEM:
            case MUSHROOM_STEW:
            case BROWN_MUSHROOM:
            case BROWN_MUSHROOM_BLOCK:
            case POTTED_BROWN_MUSHROOM:
            case POTTED_RED_MUSHROOM:
            case RED_MUSHROOM:
            case RED_MUSHROOM_BLOCK:
            case BAKED_POTATO:
            case COCOA_BEANS:
            case COCOA:
            case DANDELION:
            case AZURE_BLUET:
            case POTTED_AZURE_BLUET:
            case POTTED_ALLIUM:
            case ALLIUM:
            case POPPY:
            case CHORUS_FLOWER:
            case CHORUS_FRUIT:
            case CHORUS_PLANT:
            case POPPED_CHORUS_FRUIT:
            case ROSE_BUSH:
            case COOKIE:
            case CAKE:
            case CANDLE_CAKE:
            case BLACK_CANDLE_CAKE:
            case BLUE_CANDLE_CAKE:
            case CYAN_CANDLE_CAKE:
            case RED_CANDLE_CAKE:
            case GRAY_CANDLE_CAKE:
            case LIME_CANDLE_CAKE:
            case PINK_CANDLE_CAKE:
            case BROWN_CANDLE_CAKE:
            case GREEN_CANDLE_CAKE:
            case WHITE_CANDLE_CAKE:
            case ORANGE_CANDLE_CAKE:
            case PURPLE_CANDLE_CAKE:
            case YELLOW_CANDLE_CAKE:
            case MAGENTA_CANDLE_CAKE:
            case LIGHT_BLUE_CANDLE_CAKE:
            case LIGHT_GRAY_CANDLE_CAKE:
            case EGG:
            case FERN:
            case LARGE_FERN:
            case POTTED_FERN:
            case KELP:
            case KELP_PLANT:
            case DRIED_KELP:
            case DRIED_KELP_BLOCK:
            case BLUE_ORCHID:
            case BLACK_DYE:
            case BLUE_DYE:
            case BROWN_DYE:
            case CYAN_DYE:
            case GRAY_DYE:
            case GREEN_DYE:
            case LIGHT_BLUE_DYE:
            case LIGHT_GRAY_DYE:
            case LIME_DYE:
            case MAGENTA_DYE:
            case ORANGE_DYE:
            case PINK_DYE:
            case PURPLE_DYE:
            case RED_DYE:
            case WHITE_DYE:
            case YELLOW_DYE:
            case ORANGE_TULIP:
            case PINK_TULIP:
            case POTTED_ORANGE_TULIP:
            case POTTED_PINK_TULIP:
            case POTTED_RED_TULIP:
            case POTTED_WHITE_TULIP:
            case RED_TULIP:
            case WHITE_TULIP:
            case POTTED_AZALEA_BUSH:
            case CORNFLOWER:
            case POTTED_CORNFLOWER:
            case CACTUS:
            case POTTED_CACTUS:
            case POTTED_BLUE_ORCHID:
            case OXEYE_DAISY:
            case POTTED_OXEYE_DAISY:
            case LILY_OF_THE_VALLEY:
            case POTTED_LILY_OF_THE_VALLEY:
            case LILAC:
            case PEONY:
            case POTTED_DANDELION:
            case POTTED_POPPY:
            case DEAD_BUSH:
            case GLOW_BERRIES:
            case GLOW_LICHEN:
            case VINE:
            case TWISTING_VINES:
            case WEEPING_VINES:
            case TWISTING_VINES_PLANT:
            case WEEPING_VINES_PLANT:
            case WITHER_ROSE:
            case POTTED_CRIMSON_FUNGUS:
            case CRIMSON_FUNGUS:
            case POTTED_DEAD_BUSH:
            case POTTED_WARPED_FUNGUS:
            case POTTED_WITHER_ROSE:
            case BEE_NEST:
            case BEEHIVE:
            case NETHER_SPROUTS:
            case TALL_GRASS:
            case SEAGRASS:
            case SEA_PICKLE:
            case TALL_SEAGRASS:
            case BIG_DRIPLEAF:
            case BIG_DRIPLEAF_STEM:
            case APPLE:
            case BREAD:
            case MAP:
            case FILLED_MAP:
            case SCULK:
            case SCULK_SENSOR:
            case SCULK_SHRIEKER:
            case SCULK_VEIN:
            case TARGET:
            case SUNFLOWER:
            case NETHER_WART:
            case NETHER_WART_BLOCK:
            case MOSS_BLOCK:
            case HONEY_BLOCK:
            case HONEY_BOTTLE:
            case HONEYCOMB:
            case HONEYCOMB_BLOCK:
            case ECHO_SHARD:
            case SHROOMLIGHT:
            case SPORE_BLOSSOM:
            case HANGING_ROOTS:
            case SMALL_DRIPLEAF:
                return Tools.HOE;
            case COD:
            case SALMON:
            case COD_BUCKET:
            case COOKED_COD:
            case COOKED_SALMON:
            case TROPICAL_FISH:
            case TROPICAL_FISH_BUCKET:
            case SALMON_BUCKET:
            case PUFFERFISH:
            case PUFFERFISH_BUCKET:
            case WARPED_FUNGUS:
            case WARPED_FUNGUS_ON_A_STICK:
            case WARPED_WART_BLOCK:
            case AXOLOTL_BUCKET:
            case BOOK:
            case KNOWLEDGE_BOOK:
            case POTION:
            case WRITABLE_BOOK:
            case WRITTEN_BOOK:
            case ENCHANTED_BOOK:
            case LILY_PAD:
            case TURTLE_EGG:
            case TURTLE_HELMET:
            case BUCKET:
            case TADPOLE_BUCKET:
            case WATER_BUCKET:
            case NAUTILUS_SHELL:
                return Tools.FISH_ROD;
            case COOKED_RABBIT:
            case SCUTE:
            case ARROW:
            case SPECTRAL_ARROW:
            case TIPPED_ARROW:
            case RABBIT:
            case RABBIT_FOOT:
            case RABBIT_HIDE:
            case LEATHER:
            case ROTTEN_FLESH:
            case BONE:
            case STRING:
            case ENDER_EYE:
            case ENDER_PEARL:
            case BLAZE_ROD:
            case BLAZE_POWDER:
            case COOKED_BEEF:
            case COOKED_CHICKEN:
            case COOKED_MUTTON:
            case COOKED_PORKCHOP:
            case PORKCHOP:
            case MUTTON:
            case CHICKEN:
            case BEEF:
            case FEATHER:
            case FERMENTED_SPIDER_EYE:
            case BOW:
            case SADDLE:
            case WHITE_WOOL:
            case BLACK_WOOL:
            case RED_WOOL:
            case BLUE_WOOL:
            case CYAN_WOOL:
            case GRAY_WOOL:
            case LIME_WOOL:
            case PINK_WOOL:
            case BROWN_WOOL:
            case GREEN_WOOL:
            case ORANGE_WOOL:
            case PURPLE_WOOL:
            case YELLOW_WOOL:
            case MAGENTA_WOOL:
            case LIGHT_BLUE_WOOL:
            case LIGHT_GRAY_WOOL:
            case INK_SAC:
            case GLOW_INK_SAC:
            case LEAD:
            case GOLDEN_APPLE:
            case ENCHANTED_GOLDEN_APPLE:
            case GOLDEN_CARROT:
            case GUNPOWDER:
            case SPONGE:
            case WET_SPONGE:
            case GHAST_TEAR:
            case MAGMA_CREAM:
            case OCHRE_FROGLIGHT:
            case PEARLESCENT_FROGLIGHT:
            case VERDANT_FROGLIGHT:
            case PHANTOM_MEMBRANE:
            case SHULKER_SHELL:
            case SLIME_BALL:
            case SLIME_BLOCK:
            case SCULK_CATALYST:
            case COBWEB:
            case BUNDLE:
            case CANDLE:
            case CYAN_CANDLE:
            case BLACK_CANDLE:
            case BLUE_CANDLE:
            case BROWN_CANDLE:
            case GRAY_CANDLE:
            case GREEN_CANDLE:
            case LIGHT_BLUE_CANDLE:
            case LIGHT_GRAY_CANDLE:
            case LIME_CANDLE:
            case MAGENTA_CANDLE:
            case ORANGE_CANDLE:
            case PINK_CANDLE:
            case PURPLE_CANDLE:
            case RED_CANDLE:
            case WHITE_CANDLE:
            case YELLOW_CANDLE:
            case RABBIT_STEW:
            case SUSPICIOUS_STEW:
            case NAME_TAG:
            case GOAT_HORN:
            case ELYTRA:
            case SHIELD:
            case SPIDER_EYE:
            case MILK_BUCKET:
            case FIRE_CHARGE:
            case FIREWORK_ROCKET:
            case FIREWORK_STAR:
            case TOTEM_OF_UNDYING:
                return Tools.MELEE_WEAPON;
            default:
                return Tools.NONE;
        }

    }
}
